/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NztGMaps;

import com.nzt.NztGdxLibrary;

public class NzMapsLib {
	NztGdxLibrary tt;
    public boolean someLibraryMethod() {
        return true;
    }
}
