/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NztGMaps;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//        NzMapsLib classUnderTest = new NzMapsLib();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
